### ISSUE TITLE
Deserializing media fails

### ISSUE THREAD

**Issue by ahmetb** [gedex/go-instagram#7]
If the response contains a media that has a user tagged on it (at some coordinate) it returns the following error:

```
instagram: error while retrieving recent media: json: cannot unmarshal object key "y" into unexported field y of type instagram.UserInPhotoPosition
```

**Comment by carbocation** [comment]
Hmm, this makes sense because the fields are unexported and therefore would be incompatible with the marshaling/unmarshaling scheme in use by the Go JSON library. I think the fix is to simply replace x and y with X and Y. Will push this change in a minute.

**Comment by carbocation** [comment]
This is currently fixed in my long-lived fork at https://github.com/carbocation/go-instagram

**Comment by ahmetb** [comment]
Hmm. Isnt this repo accepting PRs anymore? @carbocation
